resources:
- repo: self

queue:
  name: Hosted VS2017

variables:
  PatchNumber: '0'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: GLDotNet.sln
    arguments: '/v:d'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: src/GLDotNet/GLDotNet.csproj
    buildProperties: 'Configuration=Release;PatchNumber=$(PatchNumber);BuildNumber=$(Build.BuildNumber)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


