pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet msbuild'
  inputs:
    command: 'custom'
    custom: 'msbuild'
    projects: build/Build.proj
    arguments: '-v:n'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    artifactName: 'GLDotNet'


